# Generated by Django 6.0.3 on 2026-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numer mieszkania'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numer domu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ulica'),
        ),
    ]
