# Generated by Django 6.0.3 on 2026-05-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('discount_type', models.CharField(choices=[('percent', 'Procentowy'), ('amount', 'Kwotowy')], default='percent', max_length=10, verbose_name='Typ rabatu')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość rabatu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Ważny od')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Ważny do')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimalna wartość zamówienia')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limit użyć')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Liczba użyć')),
            ],
            options={
                'verbose_name': 'Kod rabatowy',
                'verbose_name_plural': 'Kody rabatowe',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='original_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.discountcode'),
        ),
    ]
