# Generated by Django 6.0.3 on 2026-05-20 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_customer_phone_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena')),
                ('estimated_days', models.CharField(blank=True, max_length=50, verbose_name='Szacowany czas dostawy')),
                ('icon', models.CharField(blank=True, help_text='Klasa ikony Font Awesome, np. fa-truck', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Metoda dostawy',
                'verbose_name_plural': 'Metody dostawy',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Koszt dostawy'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa metody dostawy'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ścieżka okładki'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Powód zwrotu')),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('approved', 'Zaakceptowany'), ('rejected', 'Odrzucony'), ('completed', 'Zrealizowany')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notatki admina')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zwrot',
                'verbose_name_plural': 'Zwroty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.return')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.shippingmethod', verbose_name='Metoda dostawy'),
        ),
    ]
